steps:
  # install the app dependencies
  #  - name: "gcr.io/cloud-builders/npm"
  #    args: [ "install" ]

  # execute the tests
  #  - name: "gcr.io/cloud-builders/npm"
  #    args: [ "run", "test" ]

  # build the container image using the docker builder
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]

  # push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "push", '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}' ]

  # Deploy the container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}
      - --region=${_LOCATION}
      - --platform=managed

images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'

substitutions:
  _LOCATION: us-central1 # must be substituted
  _REPOSITORY: repo # must be substituted
  _GCR_REGION: us # must be substituted
  _SERVICE_NAME: service-name # must be substituted